- apiVersion: v1
  kind: Secret
  metadata:
    name: db-credentials
  type: Opaque
  stringData:
    {{$cred := .Values.petclinicDatabase.config.credential}}
    username: {{- if .Values.petclinicDatabase.config.credential.username}}
                {{- .Values.petclinicDatabase.config.credential.username | b64enc | quote}}
              {{- else}}
                {{randAlphaNum 12 | b64enc | quote}}
              {{- end}}
    password: {{- if .Values.petclinicDatabase.config.credential.password}}
                {{- .Values.petclinicDatabase.config.credential.password | b64enc | quote}}
              {{- else}}
                {{- randAlphaNum 12 | b64enc | quote}}
              {{- end}}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: db-settings
  data:
    database.name: {{.Values.petclinicDatabase.config.name | quote}}
