apiVersion: v1
kind: Service
metadata:
  name: petclinic-db-service
  labels:
    app: petclinic
spec:
  selector:
    app: db
  type: NodePort
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001
