apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
stringData:
  {{- with .Values.petclinicDatabase.config}}
  username: {{if and .credential .credential.username}}{{.credential.username | quote}}{{else}}{{randAlphaNum 12 | b64enc | quote}}{{end}}
  password: {{if and .credential .credential.password}}{{.credential.password | quote}}{{else}}{{randAlphaNum 12 | b64enc | quote}}{{end}}
  {{- end}}
