apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment-without-db-binding
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: ralfueberfuhr/spring-petclinic-rest:latest
        imagePullPolicy: Always
        # https://medium.com/@sats17/resolving-kubernetes-pod-oomkilled-errors-for-java-spring-boot-applications-conquering-out-of-7a48e1f6db04
        resources:
          requests:
            memory: "400Mi"
            cpu: "200m"
          limits:
            memory: "1300Mi"
            cpu: "600m"
        ports:
        - containerPort: 8080
        env:
        # https://medium.com/@sats17/resolving-kubernetes-pod-oomkilled-errors-for-java-spring-boot-applications-conquering-out-of-7a48e1f6db04
        - name: JAVA_OPTS
          value: "-XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=60.0"
        - name: CONTEXT_ROOT
          value: "/"
        #- name: SPRING_APPLICATION_JSON
        #  value: '{"logging":{"level":{"root":"TRACE"}}}'
        - name: DB_DS_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_DS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_DS_DRIVERCLASS
          valueFrom:
            configMapKeyRef:
              name: app-settings
              key: database.driver
        - name: DB_JPA_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-settings
              key: database.type
        - name: DB_JPA_DATABASE_PLATFORM
          valueFrom:
            configMapKeyRef:
              name: app-settings
              key: database.dialect
        - name: DB_DS_URL
          valueFrom:
            configMapKeyRef:
              name: app-settings
              key: database.url
        - name: PROBES_CONTEXT_ROOT
          value: "/"
        - name: PROBES_PORT
          value: "8081"

