apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-deployment
  labels:
    app: petclinic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: petclinic
        image: ralfueberfuhr/spring-petclinic-rest:latest
        ports:
        - containerPort: 8080
        env:
        - name: CONTEXT_ROOT
          value: /
        - name: SPRING_PROFILES_ACTIVE
          value: cloud
