apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: petclinic 
  name: petclinic-route
spec:
  host: petclinic-ueberfuhr.apps.devqs.ars.de
  to:
    kind: Service
    name: petclinic-service
  port:
    targetPort: 8080
