apiVersion: v1
kind: ConfigMap
metadata:
  name: app-settings
data:
  database.name: "{{.Values.petclinicDatabase.config.name}}"
  database.driver: "org.postgresql.Driver"
  database.type: "POSTGRESQL"
  database.dialect: "org.hibernate.dialect.PostgreSQLDialect"
  database.url: "jdbc:postgresql://database.{{.Values.petclinicApp.route.host}}:30001/{{.Values.petclinicDatabase.config.name}}"
