apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: petclinic
  name: petclinic-route
spec:
  host: "{{.Values.petclinicApp.route.domain}}.{{.Values.petclinicApp.route.host}}"
  to:
    kind: Service
    name: petclinic-service
  port:
    targetPort: 8080
