---
name: CI-Build to DockerHub

on:
  pull_request:
    branches:
     - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.editorconfig'
      - '.github/workflows/native-image.yml'
      - 'openshift/**'
      - 'argocd-minikube/**'
      - 'terraform/**'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.editorconfig'
      - '.github/workflows/native-image.yml'
      - 'openshift/**'
      - 'argocd-minikube/**'
      - 'terraform/**'
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from SCM
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build App
        run: mvn -B package --file pom.xml -Djacoco.skip=true -DdisableXmlReport=true
      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/spring-petclinic-rest.jar
      - name: Upload POM
        uses: actions/upload-artifact@v4
        with:
          name: pom
          path: pom.xml
      - name: Upload Container Configuration Files
        uses: actions/upload-artifact@v4
        with:
          name: container
          path: docker/**
      - name: Upload Helm Chart Files
        uses: actions/upload-artifact@v4
        with:
          name: helmchart
          path: helm/**
      - name: Upload Database Configuration Files
        uses: actions/upload-artifact@v4
        with:
          name: database
          path: src/main/resources/db/**

  build-app-container:
    needs:
      - build-app
    runs-on: ubuntu-latest
    steps:
      - name: Restore App
        uses: actions/download-artifact@v4
        with:
          name: app
          path: target
      - name: Restore POM
        uses: actions/download-artifact@v4
        with:
          name: pom
      - name: Restore Container Configuration Files
        uses: actions/download-artifact@v4
        with:
          name: container
          path: docker
      # (optionally) https://github.com/docker/buildx
      # (optionally) https://github.com/docker/metadata-action
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Retrieve project version from pom
        run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Show extracted Maven project version
        run: echo 'Project version is ${{ env.PROJECT_VERSION }}'
      - name: Build Container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          tags: |
            ralfueberfuhr/spring-petclinic-rest:latest
            ralfueberfuhr/spring-petclinic-rest:${{ env.PROJECT_VERSION }}
          labels: |
            repository=${{ github.repositoryUrl }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Write Summary
        run: echo "Successfully built container image 'ralfueberfuhr/spring-petclinic-rest:${{ env.PROJECT_VERSION }}'" >> $GITHUB_STEP_SUMMARY
  build-database-container:
    needs:
      - build-app
    runs-on: ubuntu-latest
    steps:
      - name: Restore Database Configuration
        uses: actions/download-artifact@v4
        with:
          name: database
          path: src/main/resources/db
      - name: Restore POM
        uses: actions/download-artifact@v4
        with:
          name: pom
      - name: Restore Container Configuration Files
        uses: actions/download-artifact@v4
        with:
          name: container
          path: docker
      # (optionally) https://github.com/docker/buildx
      # (optionally) https://github.com/docker/metadata-action
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Retrieve project version from pom
        run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Show extracted Maven project version
        run: echo 'Project version is ${{ env.PROJECT_VERSION }}'
      - name: Build Container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/db/Dockerfile
          tags: |
            ralfueberfuhr/spring-petclinic-db:latest
            ralfueberfuhr/spring-petclinic-db:latest-postgresql
            ralfueberfuhr/spring-petclinic-db:${{ env.PROJECT_VERSION }}
            ralfueberfuhr/spring-petclinic-db:${{ env.PROJECT_VERSION }}-postgresql
          labels: |
            repository=${{ github.repositoryUrl }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Write Summary
        run: echo "Successfully built container image 'ralfueberfuhr/spring-petclinic-db:${{ env.PROJECT_VERSION }}'" >> $GITHUB_STEP_SUMMARY
  build-oci-container:
    needs:
      - build-app
    runs-on: ubuntu-latest
    steps:
      - name: Restore Helm Chart Files
        uses: actions/download-artifact@v4
        with:
          name: helmchart
          path: helm
      # https://github.com/appany/helm-oci-chart-releaser/blob/main/README.md
      - name: Build & Push
        if: github.event_name != 'pull_request'
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: spring-petclinic-oci
          repository: ralfueberfuhr
          tag: 0.0.1
          path: helm/chart
          registry: registry-1.docker.io
          registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
          registry_password: ${{ secrets.DOCKERHUB_PASSWORD }}
