---
name: CI-Build to DockerHub

on:
  pull_request:
    branches:
     - main
  push:
    branches:
      - main
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from SCM
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build App
        run: mvn -B package --file pom.xml -Djacoco.skip=true -DdisableXmlReport=true
      - name: Upload App
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: target/app.jar
      - name: Upload POM
        uses: actions/upload-artifact@v4
        with:
          name: pom
          path: pom.xml
      - name: Upload Container Configuration Files
        uses: actions/upload-artifact@v4
        with:
          name: container
          path: docker/**

  build-container:
    needs:
      - build-app
    runs-on: ubuntu-latest
    steps:
      - name: Restore App
        uses: actions/download-artifact@v4
        with:
          name: app
      - name: Restore POM
        uses: actions/download-artifact@v4
        with:
          name: pom
      - name: Restore Container Configuration Files
        uses: actions/download-artifact@v4
        with:
          name: container
      # (optionally) https://github.com/docker/buildx
      # (optionally) https://github.com/docker/metadata-action
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Retrieve project version from pom
        run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Show extracted Maven project version
        run: echo 'Project version is ${{ env.PROJECT_VERSION }}'
      - name: Build Container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: |
            ralfueberfuhr/spring-petclinic-rest:latest
            ralfueberfuhr/spring-petclinic-rest:${{ env.PROJECT_VERSION }}
          labels: |
            repository=${{ github.repositoryUrl }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Write Summary
        run: echo "Successfully built container image 'ralfueberfuhr/spring-petclinic-rest:${{ env.PROJECT_VERSION }}'" >> $GITHUB_STEP_SUMMARY
