---
name: Native Image Build to DockerHub

on:
  workflow_dispatch:
    inputs:
      builderImage:
        description: 'Image that is used as Build Container'
        required: true
        default: ralfueberfuhr/graalvm-ce:ol9-java17-maven-22.3.3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout from SCM
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Retrieve project version from pom
        run: echo "PROJECT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Show extracted Maven project version
        run: echo 'Project version is ${{ env.PROJECT_VERSION }}'
      - name: Build Container
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/native-image/Dockerfile
          build-args: |
            BUILDER_IMAGE=${{ inputs.builderImage }}
          tags: |
            ralfueberfuhr/spring-petclinic-rest:latest-native
            ralfueberfuhr/spring-petclinic-rest:${{ env.PROJECT_VERSION }}-native
          labels: |
            repository=${{ github.repositoryUrl }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Write Summary
        run: echo "Successfully built container image 'ralfueberfuhr/spring-petclinic-rest:${{ env.PROJECT_VERSION }}-native'" >> $GITHUB_STEP_SUMMARY
